// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: endorser.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XendorserClient is the client API for Xendorser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XendorserClient interface {
	EndorserCall(ctx context.Context, in *EndorserRequest, opts ...grpc.CallOption) (*EndorserResponse, error)
}

type xendorserClient struct {
	cc grpc.ClientConnInterface
}

func NewXendorserClient(cc grpc.ClientConnInterface) XendorserClient {
	return &xendorserClient{cc}
}

func (c *xendorserClient) EndorserCall(ctx context.Context, in *EndorserRequest, opts ...grpc.CallOption) (*EndorserResponse, error) {
	out := new(EndorserResponse)
	err := c.cc.Invoke(ctx, "/protos.xendorser/EndorserCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XendorserServer is the server API for Xendorser service.
// All implementations should embed UnimplementedXendorserServer
// for forward compatibility
type XendorserServer interface {
	EndorserCall(context.Context, *EndorserRequest) (*EndorserResponse, error)
}

// UnimplementedXendorserServer should be embedded to have forward compatible implementations.
type UnimplementedXendorserServer struct {
}

func (UnimplementedXendorserServer) EndorserCall(context.Context, *EndorserRequest) (*EndorserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndorserCall not implemented")
}

// UnsafeXendorserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XendorserServer will
// result in compilation errors.
type UnsafeXendorserServer interface {
	mustEmbedUnimplementedXendorserServer()
}

func RegisterXendorserServer(s grpc.ServiceRegistrar, srv XendorserServer) {
	s.RegisterService(&Xendorser_ServiceDesc, srv)
}

func _Xendorser_EndorserCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndorserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XendorserServer).EndorserCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.xendorser/EndorserCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XendorserServer).EndorserCall(ctx, req.(*EndorserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Xendorser_ServiceDesc is the grpc.ServiceDesc for Xendorser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Xendorser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.xendorser",
	HandlerType: (*XendorserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EndorserCall",
			Handler:    _Xendorser_EndorserCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "endorser.proto",
}
